Document: ifdokccid
Title: Debian ifdokccid Manual
Author: <insert document author here>
Abstract: This manual describes what ifdokccid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ifdokccid/ifdokccid.sgml.gz

Format: postscript
Files: /usr/share/doc/ifdokccid/ifdokccid.ps.gz

Format: text
Files: /usr/share/doc/ifdokccid/ifdokccid.text.gz

Format: HTML
Index: /usr/share/doc/ifdokccid/html/index.html
Files: /usr/share/doc/ifdokccid/html/*.html
